// Low level design for parking lot system


// Requirements
/*
1. Multiple Floor
2. Multiple entry and exit points
3. customer can collect parking tickets from entry and pay at exit
4. Customer can pay ticket to authorise parking attendent or at the automated exit panel or at the customer info panel which is present at teh each floor
5. Can pay via cash or credit cards
6. Should support multiple type of parkings like Caomapct, Large, MotorCycle
7. Some spot for electric cars where they can charge 
8. Each parking floor should have panel to show the data, a panel on the ground floor to show the data
9. The System should support per hour pricing model

// Actors

// Top use cases

// class diagrams -- interface and abstract class

// implementatioins


